# Generated by Django 4.2.15 on 2024-08-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_options_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.IntegerField(choices=[(0, 'Adventure'), (1, 'Romance'), (2, 'Fantasy'), (3, 'Science Fiction'), (4, 'Mystery'), (5, 'Horror'), (6, 'Thriller'), (7, 'Historical Fiction'), (8, 'Comedy'), (9, 'Drama'), (10, 'Detective/Crime'), (11, 'Western'), (12, 'Biography/Autobiography'), (13, 'Gothic'), (14, 'Dystopian'), (15, 'Epic'), (16, 'Coming-of-Age'), (17, 'Slice of Life'), (18, 'Tragedy'), (19, 'Mythology')], default=0),
        ),
    ]
