# Generated by Django 4.2.15 on 2024-08-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(0, 'Fiction'), (1, 'Non-Fiction')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.IntegerField(choices=[(0, 'Adventure'), (1, 'Romance'), (2, 'Fantasy'), (3, 'Science'), (4, 'Mystery'), (5, 'Horror'), (6, 'Thriller'), (7, 'Historical'), (8, 'Comedy'), (9, 'Drama'), (10, 'Detective/Crime'), (11, 'Western'), (12, 'Biography/Autobiography'), (13, 'Gothic'), (14, 'Dystopian'), (15, 'Epic'), (16, 'Coming-of-Age'), (17, 'Slice of Life'), (18, 'Tragedy'), (19, 'Mythology'), (20, 'Technology')], default=0),
        ),
    ]
